language: python
python:
  - "3.7"

services:
  - docker

dist: "bionic"
jobs:

install:
  - ./.ci/install-devtools.sh
  - ./.ci/install-requirements.sh

script:
  - ./.ci/style-check.sh
  - ./.ci/unit-tests.sh
  - ./.ci/build.sh
  - ./.ci/service-tests.sh
  - ./.ci/releases.sh
  - source releases.env

deploy:
- provider: releases
  api_key: ${GH_TOKEN}
  file_glob: true
  file:
    - "${TRAVIS_BUILD_DIR}/dist/*"
    - "${TRAVIS_BUILD_DIR}/CHANGELOG.md"
  skip_cleanup: true
  draft: ${GH_RELEASE_DRAFT} = true
  name: ${GH_RELEASE_NAME}
  body: ${GH_RELEASE_BODY}
  prerelease: ${GH_RELEASE_CANDIDATE}
  on:
    tags: true
    branch: master

- provider: script
  script: bash .ci/deploy-pypi.sh ${TRAVIS_BUILD_DIR}/dist/${PYTHON_PKG_NAME}*
  skip_cleanup: true
  on:
    tags: true
    branch: master

env:
  global:
    - PIPENV_VENV_IN_PROJECT=1
    - PIPENV_IGNORE_VIRTUALENVS=1
    - PYTHON_PKG_PATH=.
    - PYTHON_PKG_NAME=wirepas_backend_client
